services:
  test-host:
    image: tjmash/ubnt:jammy
    container_name: test-host
    ports:
      - 22:22
    tty: true
    volumes:
      - ./ansible-keys:/app/data/ansible-keys
    networks:
      - semaui-net

networks:
  semaui-net:
    driver: bridge
